
GET http://localhost:3000/

###
// show all order by specific user 
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZTVmMzVhMzlhODE2YTYzNjA4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTY0NzEzODksImV4cCI6MTcxNjU1Nzc4OX0.GKkeb0hYV6bxucC15FkuoR0EtU2YqqggOBC0A1e89QE

###
// create new order by cart
POST http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZTVmMzVhMzlhODE2YTYzNjA4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTY0NzEzODksImV4cCI6MTcxNjU1Nzc4OX0.GKkeb0hYV6bxucC15FkuoR0EtU2YqqggOBC0A1e89QE
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Rossi",
    "address": "Via Roma 123",
    "city": "Milano",
    "region": "Lombardia",
    "state": "Italy",
    "postalCode": "20100"
}

// show order by specific id
###
GET http://localhost:3000/api/orders/663e4f2b35a39a816a63609b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Mzc2MmU5Mzc5NDJmNWE4ZTJjMTNkZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNTE4NDMsImV4cCI6MTcxNTQzODI0M30.Io4b8jsnhD40UVYp2iGStfpsVuU0JN0q3uQ5FRAQykA

// update status order by id (only ADMIN)
###
PUT http://localhost:3000/api/orders/663e4f2b35a39a816a63609b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Mzc2MmU5Mzc5NDJmNWE4ZTJjMTNkZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNTE4NDMsImV4cCI6MTcxNTQzODI0M30.Io4b8jsnhD40UVYp2iGStfpsVuU0JN0q3uQ5FRAQykA
Content-Type: application/json

{
    "status": "cancelled"
}

// delete order by id (only ADMIN)
###
DELETE http://localhost:3000/api/orders/663e4af1aac787c4026c1d65
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Mzc2MmU5Mzc5NDJmNWE4ZTJjMTNkZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNTE4NDMsImV4cCI6MTcxNTQzODI0M30.Io4b8jsnhD40UVYp2iGStfpsVuU0JN0q3uQ5FRAQykA
