
GET http://localhost:3000/


###
// register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "ADMIN",
    "surname": "CognomeADMIN",
    "email": "admin@admin.it",
    "password": "test123"
}

###
// admin register
POST http://localhost:3000/api/auth/admin/register
Content-Type: application/json

{
    "name": "ADMIN",
    "surname": "CognomeADMIN",
    "email": "admin@admin.it",
    "password": "test123"
}

###
//login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "provaUser2@gmail.com",
    "password": "test123"
}

###logout
GET http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzRlMTg0NGU3Y2Y0YjEyMjY5OGUxMyIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQ3NDE4OTksImV4cCI6MTcxNDgyODI5OX0.YnsIA7Yd6sRn-QiERaz_noaT0y36lrx7ql_CsiGCKA0

###
// show user info
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Mzc2MmU5Mzc5NDJmNWE4ZTJjMTNkZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQ5MTA5OTQsImV4cCI6MTcxNDk5NzM5NH0.2zYUXr8xzn4oDwzbY2A2aRaCqlEezOjjcyiYasx-si4
