
GET http://localhost:3000/


###
// register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "provaUser5343245435",
    "surname": "cognomeUser4",
    "email": "provaUse534435323@gmail.com",
    "password": "test123"
}

###
//login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "provaUser5343@gmail.com",
    "password": "test123"
}

###logout
GET http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTY2YzRiMmZjMmEyMGVjYzhmNTEyMCIsImVtYWlsIjoicHJvdmFVc2VyNTM0M0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDY1Nzc3OCwiZXhwIjoxNzE0NzQ0MTc4fQ.ipS8KxQC5VRdfU43IVskbzn1c4bOPn9_Qv-YliZQ_zU

###
// show user info
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTY2YzRiMmZjMmEyMGVjYzhmNTEyMCIsImVtYWlsIjoicHJvdmFVc2VyNTM0M0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNDY1Nzc3OCwiZXhwIjoxNzE0NzQ0MTc4fQ.ipS8KxQC5VRdfU43IVskbzn1c4bOPn9_Qv-YliZQ_zU