
GET http://localhost:3000/


###
// register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "provaUser5343245435",
    "surname": "cognomeUser4",
    "email": "provaUser5344353@gmail.com",
    "password": "test123"
}

###
//login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "provaUser5343@gmail.com",
    "password": "test123"
}

###logout
GET http://localhost:3000/api/auth/logout

###
// show user info
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTY2YzRiMmZjMmEyMGVjYzhmNTEyMCIsImVtYWlsIjoicHJvdmFVc2VyNTM0M0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMzgxNTIyNywiZXhwIjoxNzEzOTAxNjI3fQ.PxYc_B_xnoVqO9W2dpyyuecEfr9F1IncYr7Op7sWLKI