
GET http://localhost:3000/

###
// show cart 
GET http://localhost:3000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZjJiMzVhMzlhODE2YTYzNjA5YiIsImVtYWlsIjoiZmFiaW8ucm9zc2lAZ21haWwuaXQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTM1OTYyNSwiZXhwIjoxNzE1NDQ2MDI1fQ.CEUcjz4pny6EgN9VqGm2dCtf5eXWvxt230ymI0pddEM

###
// add new product to cart
POST http://localhost:3000/api/cart/add/663e5afae6c6a62b7a908cf3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZjJiMzVhMzlhODE2YTYzNjA5YiIsImVtYWlsIjoiZmFiaW8ucm9zc2lAZ21haWwuaXQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTM1OTYyNSwiZXhwIjoxNzE1NDQ2MDI1fQ.CEUcjz4pny6EgN9VqGm2dCtf5eXWvxt230ymI0pddEM


// delete producut by id
###
DELETE  http://localhost:3000/api/cart/remove/663e5afae6c6a62b7a908cf3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZjJiMzVhMzlhODE2YTYzNjA5YiIsImVtYWlsIjoiZmFiaW8ucm9zc2lAZ21haWwuaXQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTM1OTYyNSwiZXhwIjoxNzE1NDQ2MDI1fQ.CEUcjz4pny6EgN9VqGm2dCtf5eXWvxt230ymI0pddEM


// delete all product by cart
###
DELETE  http://localhost:3000/api/cart/clear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZjJiMzVhMzlhODE2YTYzNjA5YiIsImVtYWlsIjoiZmFiaW8ucm9zc2lAZ21haWwuaXQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTM1OTYyNSwiZXhwIjoxNzE1NDQ2MDI1fQ.CEUcjz4pny6EgN9VqGm2dCtf5eXWvxt230ymI0pddEM
