
GET http://localhost:3000/

###
// show all users order 
GET http://localhost:3000/api/orders

###
// create new order by cart
POST http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Mzc2MmU5Mzc5NDJmNWE4ZTJjMTNkZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTQ5MjE2MjYsImV4cCI6MTcxNTAwODAyNn0.2EpYwiO60O6o1r-6H6CiZiFfrwZaSngXvzvsAfcSEjs
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Rossi",
    "address": "Via Roma 123",
    "city": "Milano",
    "region": "Lombardia",
    "state": "Italy",
    "postalCode": "20100"
}


// TODO forse si deve togliere
// delete producut by id
###
DELETE  http://localhost:3000/api/cart/remove/
