
GET http://localhost:3000/

###
// show order 
GET http://localhost:3000/api/orders
Content-Type: application/json

{
    "userId": "66144d3ecd968b084ebe34c5"
}

###
// add new order by cart
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "cartId": "6616a9ffca4167fcca78d422"
}

// TODO forse si deve togliere
// delete producut by id
###
DELETE  http://localhost:3000/api/cart/remove/


// TODO forse si deve togliere 
// delete all product by cart 
###
DELETE  http://localhost:3000/api/cart/clear
