
GET http://localhost:3000/

###
// show all product
GET http://localhost:3000/api/products/

###
// add new product(admin)
POST http://localhost:3000/api/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZTVmMzVhMzlhODE2YTYzNjA4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNjA5MzQsImV4cCI6MTcxNTQ0NzMzNH0.YpdZwY_3Xs2PYHeKiIFMEiI1-GZQ1ngYuaMry02t0yg
Content-Type: application/json

{
    "name": "Smartphone",
    "brand": "ABC Electronics",
    "quantity": 100,
    "price": 599.99,
    "sale": 0.2
}


###
// get product by id
GET http://localhost:3000/api/products/66379b4feff2fe55298706f1


// delete producut by id (admin)
###
DELETE  http://localhost:3000/api/products/663e54b97f30e5ddf566a115
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZTVmMzVhMzlhODE2YTYzNjA4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNjA5MzQsImV4cCI6MTcxNTQ0NzMzNH0.YpdZwY_3Xs2PYHeKiIFMEiI1-GZQ1ngYuaMry02t0yg

// updrade product by id (admin)
###
PUT http://localhost:3000/api/products/663e54b97f30e5ddf566a115
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2U0ZTVmMzVhMzlhODE2YTYzNjA4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uaXQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTUzNjA5MzQsImV4cCI6MTcxNTQ0NzMzNH0.YpdZwY_3Xs2PYHeKiIFMEiI1-GZQ1ngYuaMry02t0yg
Content-Type: application/json

{
    "name": "Upgraded",
    "brand": "Dream Brands Inc.",
    "quantity": 80,
    "price": 99.99,
    "sale": 0.2
}